#!/bin/bash
echo "==============================================="
echo "API Testing with Burp Suite Lab"
echo "==============================================="
echo ""
echo "Starting Burp Suite Professional..."
echo "The vulnerable API is running at http://localhost:8080"
echo ""
echo "Quick Setup Instructions:"
echo "1. Configure Burp proxy to 127.0.0.1:8080"
echo "2. Set browser proxy to use Burp"
echo "3. Navigate to http://localhost:8080/api/products"
echo ""
echo "Lab files location: ~/burp-api-lab/"
echo "Available endpoints: ~/burp-api-lab/api-endpoints.txt"
echo "Test data: ~/burp-api-lab/test-data.json"
echo ""
echo "The vulnerable API includes:"
echo "- SQL injection vulnerabilities"
echo "- Broken authentication"
echo "- IDOR (Insecure Direct Object Reference)"
echo "- Missing rate limiting"
echo "- Weak API key validation"
echo ""
echo "==============================================="
echo ""
burpsuite &
